### PR TITLE
Updates tags to v0.1.2

### PR DESCRIPTION
**Pull request by JoshVanL**
Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>

/assign @SgtCoDFish

### CODE REVIEW

**Comment by JoshVanL** [comment]
Just double checking the tests have been fixed.

**Comment by irbekrm** [comment]
`/hold` because of the tests

**Comment by JoshVanL** [comment]
Separate issue that needs to be investigated.

/retest

**Comment by JoshVanL** [comment]
urgh.

/retest

**Comment by irbekrm** [comment]
Do you know why it's timing out?

**Comment by JoshVanL** [comment]
@irbekrm An issue with the container I am using it looks like. Something to look into another time.

/retest

**Comment by JoshVanL** [comment]
```
 Downloading istio-1.8.2 from https://github.com/istio/istio/releases/download/1.8.2/istio-1.8.2-linux-amd64.tar.gz ...
make: *** [Makefile:71: /home/prow/go/src/github.com/cert-manager/istio-csr/bin/istioctl-1.8.2] Error 7 
```

:upside_down_face: 
/retest

**Pull request merged**
