### PR TITLE
Adds configs for istio 1.12.2 1.13.1 - Makes 1.13 default

### PR DESCRIPTION
**Pull request by JoshVanL**
Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>

Also updates Helm version to `v3.5.0`, cert-manager installation to `v1.7.0`

/hold

### CODE REVIEW

**Comment by irbekrm** [comment]
I've tested the configs with latest istio-csr release and Istio 1.12.2 and 1.13.1 respectively and all worked 👍🏼 

Adding a hold in case you want to update Istio 1.13.0 -> 1.13.1 which has come out whilst I was slow to review this PR https://istio.io/latest/news/releases/1.13.x/announcing-1.13.1/

/lgtm
/approve
/hold

**Comment by JoshVanL** [comment]
Needs https://github.com/jetstack/testing/pull/644 to pass v1.13.1 istio e2e tetsts

**Pull request merged**
