### PR TITLE
Limit namespaces for configmaps, useful for multitenant environments

### PR DESCRIPTION
**Pull request by knutejohKLP**
When running in a multitenant environment, limit the namespaces the configmaps are written to be using the built in --configmap-namespace-selector option in istio-csr

### CODE REVIEW

**Comment by SpectralHiss** [comment]
This seems to work fine, i just want to have another example in documentation for non-maistra use-case like perhaps `istio-injection=enabled` or `istio.io/rev=canary`

**Comment by SpectralHiss** [comment]
I did notice that the reconciliation loop doesn't work well if the namespace was already created at the time of adding the namespace selector (an upgrade scenario), so i will double check that and open a separate issue if needed.

**Comment by SpectralHiss** [comment]
@SgtCoDFish tested, waiting for your approval.

**Review by SgtCoDFish — APPROVED** [review]
/lgtm
/approve

Approving based on @SpectralHiss 's testing. Thanks very much for your contribution!

**Pull request merged**
