### PR TITLE
Update go to 1.19, update dependencies

### PR DESCRIPTION
**Pull request by malovme**
Bumps Go from `1.18` to `1.19`

and dependencies

github.com/cert-manager/cert-manager from `v1.8.1` to `v1.11.0`
github.com/fsnotify/fsnotify from `v1.5.4` to `v1.6.0`
github.com/onsi/gomega from `v1.19.0` to `v1.26.0`
github.com/prometheus/client_golang from `v1.12.2` to `v1.14.0`
github.com/spf13/cobra from `v1.4.0` to `v1.6.1`
github.com/stretchr/testify from `v1.7.1` to `v1.8.1`
google.golang.org/grpc from `v1.47.0` to `v1.49.0`
google.golang.org/protobuf from `v1.28.0` to `v1.28.1`
k8s.io/api from `v0.24.1` to `v0.26.1`
k8s.io/apimachinery from `v0.24.1` to `v0.26.1`
k8s.io/cli-runtime from `v0.24.1` to `v0.26.1`
k8s.io/client-go from `v0.24.1` to `v0.26.1`
k8s.io/component-base from `v0.24.1` to `v0.26.1`
k8s.io/klog/v2 from `v2.60.1` to `v2.90.0`
k8s.io/utils from `v0.0.0-20220210201930-3a6ce19ff2f9` to `v0.0.0-20230209194617-a36077c30491`
sigs.k8s.io/controller-runtime from `v0.12.1` to `v0.14.4`

### CODE REVIEW

**Comment by malovme** [comment]
@inteon likely this https://github.com/jetstack/testing/pull/793 needs to land to make tests happy

**Comment by inteon** [comment]
@malovme I updated some additional dependencies

**Comment by malovme** [comment]
> @malovme I updated some additional dependencies

Thank you! I noticed they were requiring changes to code so thought to left istio packages updates to separate PR, but that's good you solved it here 👍

**Comment by malovme** [comment]
> @malovme I think we still need to add a test for k8s 1.26 + istio v1.16. Could you create a PR for that?

https://github.com/jetstack/testing/pull/794

**Comment by malovme** [comment]
looks like ca-rotation test is failing due to
```
>> installing istio
./test/carotation/setup-3.sh: line 29: ./bin/istioctl-1.16.2: No such file or directory
```
and one test is failing with istio 1.17:
```
• Failure [1.298 seconds]
[cert-manager istio agent] mTLS correctness
/home/prow/go/src/github.com/cert-manager/istio-csr/test/e2e/framework/framework.go:81
  it should enforce mTLS, and fail for non-mTLS to mTLS [It]
  /home/prow/go/src/github.com/cert-manager/istio-csr/test/e2e/suite/mtls/mtls.go:122
  Unexpected error:
              
      <*errors.errorString | 0xc00033f2c0>: {
          s: "expected single sleep pod in ns \"foo\", got=0",
      }
      expected single sleep pod in ns "foo", got=0
  occurred
  /home/prow/go/src/github.com/cert-manager/istio-csr/test/e2e/suite/mtls/mtls.go:135
```

**Comment by inteon** [comment]
@malovme `gcr.io/istio-release/pilot:1.17.0` is not yet available, do we just wait a couple more days or is there a reason this has not been released here?

**Comment by malovme** [comment]
> link

yes, let's wait

**Comment by malovme** [comment]
> I fixed the first issue `line 29: ./bin/istioctl-1.16.2: No such file or directory`.
> 
> @malovme `gcr.io/istio-release/pilot:1.17.0` is not yet available, do we just wait a couple more days or is there a reason this has not been released here?

yes, let's wait once images will be published

**Comment by SgtCoDFish** [comment]
NB: The changes to jetstack/testing ([this PR](https://github.com/jetstack/testing/pull/794)) have broken tests for all istio-csr pull requests until this merges successfully. I think we need to either revert https://github.com/jetstack/testing/pull/794 or  change the test config such that the new tests for new istio versions are optional and don't run by default, until they can be made to pass.

**Comment by malovme** [comment]
@SgtCoDFish I filed https://github.com/jetstack/testing/pull/795 to remove v1.17 until it's image will be published

**Comment by inteon** [comment]
Thank you for the upgrades
/approve
/lgtm

**Review by SgtCoDFish — APPROVED** [review]
/approve

(I'm aware that the OWNERS file here is out of date!)

**Pull request merged**
