### PR TITLE
Add CustomClientCertificateDuration

### PR DESCRIPTION
**Pull request by volkorny**
Add CustomClientCertificateDuration

Hello Team,

This PR is not yet ready for merging, as I still need to add the corresponding tests and update the Helm chart. However, I’d appreciate your feedback on the current changes before proceeding further.

In our service mesh, we aim to increase the certificate duration beyond 24 hours. I noticed a similar request in [cert-manager/istio-csr issue #176.](https://github.com/cert-manager/istio-csr/issues/176)

Could you please review my changes and let me know if they seem reasonable?

### CODE REVIEW

**Comment by SgtCoDFish** [comment]
/ok-to-test

Hey, thanks for raising this. I'm heading out for the holidays soon and won't be back until the new year. This does seem a reasonable thing to add. In any case, I'll enable testing so you're able to use the CI properly!

Thanks for the contribution - if you need a review, cert-manager [slack](https://cert-manager.io/docs/contributing/#slack) is probably the place to ask!

**Comment by volkorny** [comment]
I have recreated PR here: https://github.com/cert-manager/istio-csr/pull/469

**Comment by volkorny** [comment]
We solved limit of 24h by specifying [SECRET_TTL](https://istio.io/latest/docs/reference/commands/pilot-agent/#secret-ttl)

**Pull request closed without merging**
