### PR TITLE
Add support for setting namespace for istio control plane. Fixes #152 

### LINKED ISSUE #152: Namespace cannot be overwritten with helm template
It would be awesome if the chart allowed overwriting the namespace of the:

- deployment.apps/cert-manager-istio-csr
- service/cert-manager-istio-csr
- service/cert-manager-istio-csr-metrics
- the istio-csr pod (replica set)
- service account

Currently, when doing:

```
helm template --name-template=cert-manager-istio-csr \
    --namespace cert-manager \
    --set "app.tls.rootCAFile=/var/run/secrets/istio-csr/ca.pem" ...
```

into a kustomization, and kubectl apply -k of the resulting yaml, those resources end up in the default namespace.

```
kubectl get all -n default
NAME                                          READY   STATUS              RESTARTS   AGE
pod/cert-manager-istio-csr-5bc67d8f65-wt85l   0/1     ContainerCreating   0          16m

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/cert-manager-istio-csr           ClusterIP   10.96.58.72     <none>        443/TCP    16m
service/cert-manager-istio-csr-metrics   ClusterIP   10.96.139.220   <none>        9402/TCP   16m
service/kubernetes                       ClusterIP   10.96.0.1       <none>        443/TCP    17m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cert-manager-istio-csr   0/1     1            0           16m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/cert-manager-istio-csr-5bc67d8f65   1         1         0       16m
```

Preferably the chart would define a way to set the namespace at the template time.

### PR DESCRIPTION
**Pull request by knutejohKLP**
Adds the ability to have istio running in a different namespace than istio-system.

### CODE REVIEW

**Comment by jewertow** [comment]
@JoshVanL can you review this PR?

**Comment by SgtCoDFish** [comment]
I'll review and approve this after some testing done by others (https://github.com/SpectralHiss might take a look). I don't have the bandwidth to properly test this locally but if SpectralHiss confirms it works well I'll happily wave this PR through (and I can cut a new release too afterwards, if needed!)

**Comment by SpectralHiss** [comment]
Hey all, i am in the process of testing this on an openshift with a service mesh on seperate namespace, the helm changes look fine, except i found a slightly unrelated issue that is relatively trivial to solve:
https://github.com/cert-manager/istio-csr/issues/191

The bigger problem i encounter in testing i suspect is not necessarily related to this PR, but i will only approve once i get this use-case working in case more changes are needed to make istio-csr work in multi-tenant/non default environments.
https://github.com/cert-manager/istio-csr/issues/192

@jewertow  I see that  you put Third party JWT in the SMCP you use [here](https://github.com/maistra/istio-operator/blob/a8241f9a0133fe32818ea45717556c37e9aba893/deploy/examples/cert-manager/smcp.yaml#L21)
Have you seen this issuer previously ? 
I am testing with latest openshift and 2.3.1:
```
oc version
Client Version: 4.12.2
Kustomize Version: v4.5.7
Server Version: 4.11.26
Kubernetes Version: v1.24.6+263df15
```

**Comment by jewertow** [comment]
I didn't notice any issue when I used `third-party-jwt`, but maybe I missed something. In that sample I configured Istio to use `third-part-jwt`, because when I used `first-party-jwt`, sidecar injection was failing due to authentication error on requesting CSR IIRC. Should istio-csr work with `first-party-jwt` as well?

**Comment by SpectralHiss** [comment]
I think this issue is related to GCP in particular, trying to add the meshCA claims https://github.com/istio/istio/issues/36221gonna try to see how to "turn that off" , the cluster is an Openshift dedicated deployed on GCP, where this is possibly done at the metadata interception level..

**Comment by SpectralHiss** [comment]
This is fine now, the issue was a red herring when the CA we set was expired.. really odd error message but definitely this PR is fine.

**Comment by SgtCoDFish** [comment]
Thanks @SpectralHiss for looking into this!

It looks like an unrelated change has broken the tests at least until #190 merges - sorry about that!

**Comment by SgtCoDFish** [comment]
https://github.com/jetstack/testing/pull/795 should have fixed it, let's try again!

/test pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-16
/test pull-cert-manager-istio-csr-k8s-v1-26-istio-v1-15

**Comment by malovme** [comment]
It is failing due to missing istio configs for 1.14.6, 1.15.5, 1.16.2 here now https://github.com/cert-manager/istio-csr/blob/main/hack/. You can see #190, but it is just rename old files with new versions

**Comment by SgtCoDFish** [comment]
I'll take a look at fixing the testing config tomorrow since I'm coming to the end of my working day :+1:

**Review by SgtCoDFish — APPROVED** [review]
/lgtm
/approve

Thanks for your work on this everyone!

**Pull request merged**
